# Generated by Django 3.2 on 2021-05-07 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='aadharno',
            field=models.CharField(max_length=15),
        ),
    ]
